@startuml 図書貸出システム

title 図書貸出システム
skinparam dpi 150



package controller {
    class UserRegisterController {
        -userModel: UserModel
        -userRegisterView: UserRegisterView
        +onClickUserRegister(name, password)
    }

    class LoginController {
        -loginView: LoginView
        -userModel: UserModel
        +onClickLogin(id, password)
    }

    class BookLendController {
        -bookModel: BookModel
        -bookLendView: BookLendView
        +onClickLend()
    }

    class BookReturnController {
        -bookModel : BookModel
        -bookLendView: BookLendView
        +onClickReturnBook()
        +selectReturnBook()
    }

    class RoomReservationController {
        -roomReservationModel: RoomReservationModel
        -roomReservationView: RoomReservationView
        +onClickRoomReservation()
        +selectRoom()
    }

    class AdminController {
        -userModel: UserModel
        -adminView: AdminView
        +onClickUserList()
        +onClickOnLoanUserList()
    }
}

package model {
    class UserModel {
        -userList: User[]
        -appendUser(user)
        -getUser(id): User
        +userRegister(name, password): User
        +login(id, password): Result<User, _>
        +getMe(): User
        +getUserList()
        +getOnLoanUserList()
    }

    class BookModel {
        -bookList: Book[]
        +lend(userId)
        +getBook(bookId)
        +getLendedList(userId)
        +returnBook(bookId)
    }

    class RoomReservationModel {
        -roomList: Room[]
        -getRoom(roomId): Room
        +getVacantRoomList()
        +roomReservation(userId, roomId)
    }
}

package view {
    class UserRegisterView {
        +moveMembersshipPage()
    }

    class LoginView {
        +moveMembersshipPage()
        +showLoginErrorMessage()
    }

    class BookLendView {
        +showLendErrorMessage()
        +moveLendCompletedPage()
    }

    class BookReturnView {
        +showLendedList(lendedList)
        +moveReturnCompletedPage()
    }

    class RoomReservationView {
        +showRoomList(roomList)
        +moveReservedPage()
        +showReservedMessage()
    }

    class AdminView {
        +showUserList(userList)
    }
}

package entity {
    entity BarcodeReader {
        +read(): UUID
    }

    entity Book {
        -rentingUser: Option<UUID>
        +lock()
        +unlock()
        +isLoan()
        +setLendByUser(userId)
        +returnBook()
    }

    entity Room {
        -reservingUser: Option<UUID>
        +lock()
        +unlock()
        +getStatus() : RoomStatus
        +reserve(userId)
    }

    enum RoomStatus {
        Vacant
        Reserved(userId: UUID)
    }

    entity User {
        -name: String
        -id: UUID
        -passHash: String
        -LendedBook: Book[]
        +newUser(name, password)
        +LoginValidation(password): Bool
        +getName()
        +getId()
        +getLendedList()
    }

    entity Client {
        -me : Option<User>
        +setLoginUser(user)
        +getMe(): User
    }

    enum Result<T, E> {
        Ok(T)
        Err(E)
    }

    enum Option<T> {
        None
        Some(T)
    }

    entity StudentUser
    User <|-- StudentUser

    entity Administrator
}

package service {
    class EncryptionService {
        +hash(str): String
    }

    class UUID {
        +newUUID() : UUID
    }
}

UserModel "1" *-- "1..*" User
BookModel "1" *-- "1..*" Book
RoomReservationModel "1" *-- "1..*" Room

UserRegisterController x--- UserModel
UserRegisterController x-- UserRegisterView
LoginController x--- UserModel
LoginController x-- LoginView
BookLendController x--- BookModel
BookLendController x-- BookLendView
BookReturnController x--- BookModel
BookReturnController x-- BookReturnView
RoomReservationController x-- RoomReservationModel
RoomReservationController x-- RoomReservationView
AdminController x--- UserModel
AdminController x-- AdminView

User x-- EncryptionService
User x-- UUID

Room -- RoomStatus
UserModel -- Result
Client -- Option
Book -- Option
Room -- Option
BookModel -- BarcodeReader

@enduml