@startuml 図書貸出システム

title 図書貸出システム
' top to bottom direction
left to right direction
skinparam dpi 150

(利用者登録) as userRegister
(貸出手続) as borrowing
(返却手続) as return
(AV室予約) as roomReservation
(ログインする) as login

(登録ユーザ一覧表示) as showAllUser
(貸出中ユーザ一覧表示) as showBorrowingUser

:一般: as user
:学生: as st
:管理者: as admin

user <|- st

borrowing ..> login :<<Include>>
return ..> login :<<Include>>
roomReservation ..> login :<<Include>>

user -- userRegister
user -- borrowing
user -- return

st - roomReservation

admin - showAllUser
admin - showBorrowingUser

@enduml